### ISSUE TITLE
Create better role definitions and management

### ISSUE THREAD

**Issue by Volte6** [Volte6/GoMud#305]
# Description

Currently roles are super vague and simplistic:
* User
* Admin
* Moderator

We need a way to define new roles, along with what commands are available to each of those roles.

The two minimally required roles (Not allowed to change) will be:
 
* User - No admin commands available
* Admin - All admin commands available

Any number of additional roles can be defined.

These can be defined in `config.yaml` in their own data node for now.

Example structure (hypothetical roles):

```
################################################################################
#
#   Roles
#   Roles are string identifiers that map to a number of command names.
#   They are used to determine what admin commands a player has access to.
#   Two roles are build in and cannot be changed:
#     - "user" - Has no admin commands
#     - "admin" - Has all admin commands
#
################################################################################
Roles:
  builder: ["room.info", "build"]
  helper: ["paz", "teleport"]
```

Consider:

Some commands may have different usages that we may want to further limit access to. For example, being able to `room 1` to teleport to room 1 is fine, but we don't necessarily want them to have access to `room edit`.

To this end either we need to split these into their own commands, or allow for getting more specific within a given command:

 ```
Roles:
  Builder: [room]
  Helper: [room.info]
```

In this example, all room commands are available to Builder, but only the room.info command is available to Helper.

Will need a user record function to check for perms:

```
if !user.HasAccess(`room.edit`) {
  // reject
}
```
